### ISSUE TITLE
Payjoin case study items for adoption push

### ISSUE THREAD

**Issue by yashrajd** [payjoin/payjoin.github.io#9]
The idea is to identify and promote adoption (where warranted) of insights and learnings from [The Payjoin Experience](https://bitcoin.design/guide/case-studies/payjoin/) case study.

**Comment by yashrajd** [comment]
This issue can list and track the items and their GitHub issues in various repos.

**Comment by DanGould** [comment]
I'm not sure what this is. Could you reword so that it is actionable (title should be an action), measurable, and achievable if you'd like to maintain it open, please
